# Generated by Django 6.0 on 2026-01-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('career', models.CharField(max_length=50)),
                ('IsCurrentStudent', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
